### ISSUE TITLE
Handling structs with nested fields

### ISSUE THREAD

**Issue by IgnisDa** [ztorage/boilermates#1]
Thanks for this project. I discovered it from a reddit thread.

How can I best handle structs with nested fields?
```rs
struct A { field1: i32, field2: i32 }

struct B { a: A }

struct C { field1: B }
```
I want boilermate to generate a struct that does not have the `c_obj.field1.a.field2` field. How can I achieve this?

**Comment by ztorage** [comment]
Hi, you could do something like that:

```rust
use boilermates::boilermates;

#[boilermates("AWithoutField2")]
struct A {
    field1: i32,

    #[boilermates(only_in_self)]
    field2: i32,
}

struct B {
    a: AWithoutField2,
}

struct C {
    field1: B,
}

fn main() {
    let a_without_field2: AWithoutField2 = AWithoutField2 { field1: 1 };
    let b = B {
        a: a_without_field2,
    };
    let c = C { field1: b };
    
    // and of course, it's easily convertible to a full `A` by filling in the value of `field2`
    let a: A = c.field1.a.into_a(3);
}
```

That's the simple answer – if you need something more advanced, keep on reading :)

Your question got me thinking, so I’ve added a feature just now to boilermates 0.2.0, where you have the `HasNo{Field}` generated trait for boilermates structs that lack a specific field.

So what you could do is:

```rust
use boilermates::boilermates;


#[boilermates("AWithoutField2")]
struct A {
    field1: i32,

    #[boilermates(only_in_self)]
    field2: i32,
}

struct B<T: HasNoField2> {
    a: T,
}

struct C<T: HasNoField2> {
    field1: B<T>,
}
```

If you parametrize `B` and `C` with a generic that has a `NoField2` trait bound, you can enforce your requirement. The struct `WithoutField2` that's generated from the boilermates macro would implement `NoField2`, while `WithField2` would not. (the trait has no functions, it's just a marker)

This will not compile:

```rust
    let a = A {
        field1: 1,
        field2: 2,
    };
    let b = B { a };
    let c = C { field1: b };
```

The errors would be:
```
error[E0277]: the trait bound `WithField2: HasNoField2` is not satisfied
  --> src/main.rs:25:17
   |
25 |     let b = B { a };
   |                 ^ the trait `HasNoField2` is not implemented for `WithField2`
   |
   = help: the trait `HasNoField2` is implemented for `WithoutField2`
note: required by a bound in `B`
  --> src/main.rs:11:13
   |
11 | struct B<T: HasNoField2> {
   |             ^^^^^^^^^^^ required by this bound in `B`
. . .
```

Now you will still be able to to do this:

```rust
    let a_without_field2: AWithoutField2 = AWithoutField2 { field1: 1 };
    let b = B {
        a: a_without_field2,
    };
    let c = C { field1: b };
```

And be able to convert to `WithField2` when you're ready:
```
    let aa: WithField2 = c.field1.a.into_with_field2(3);
```

Hope this helps!
Also, can I ask what's the use case?

**Comment by IgnisDa** [comment]
Thanks, I will try to fit it to my codebase later.

As for the use-case, I have a [`DoneWorkout`](https://github.com/IgnisDa/ryot/blob/main/apps/backend/src/fitness/exercise/logic.rs) struct, which holds information about a workout session. But some fields on the struct are calculated (for example, total weight lifted). I want to generate another struct without these calculated fields. As you can see, the struct itself is highly nested, hence my original question :).
