### ISSUE TITLE
Using `only_in` results in `struct has no field named`

### ISSUE THREAD

**Issue by IgnisDa** [ztorage/boilermates#3]
I have [this](https://github.com/IgnisDa/ryot/blob/2dc9a7047369cdf5b8a06bc44363e12d3c227b25/apps/backend/src/fitness/exercise/logic.rs) code. I want to generate a `struct InProgressExercise` which does not have one of the fields `in_progress_sets`.

I am getting this error:
![image](https://github.com/ztorage/boilermates/assets/60938164/f97c8208-9f84-4a4e-9690-234e129509c1)

I tried removing all the derives, but it still does not work.

**Comment by ztorage** [comment]
Right, this is because you have:

```rust
    #[boilermates(only_in("InProgressExercise"))]
    pub in_progress_sets: Vec<InProgressSetRecord>,
```

`only_in` indicates that the `in_progress_sets` SHOULD BE in `InProgressExercise` and NOT in `DoneExercise`.
You should have used `only_in_self` or `only_in("DoneExercise")` or `not_in("InProgressExercise")`.
